# Generated by Django 2.1.7 on 2019-02-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20190222_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='e_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='s_date',
            field=models.DateField(auto_now=True),
        ),
    ]
